services:
  database:
    image: "mongo:5.0"
    env_file: .env
    container_name: anigelo-web-db
    ports:
      - 27017-27019:27017-27019
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$APIGELO_DB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$APIGELO_DB_PWD
    volumes:
      - $APIGELO_DB_PATH:/data/db
  api:
    image: "mangelarilla/apigelo:1.0"
    env_file: .env
    ports:
      - "8088:8080"
    depends_on:
      - database
